#knp_doctrine_behaviors:
#    blameable:      false
#    geocodable:     ~     # Here null is converted to false
#    loggable:       ~
#    sluggable:      true
#    soft_deletable: true
    # All others behaviors are disabled