version: '3'
services:
  web:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/var/cache
      - /var/www/html/var/log
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
  redis:
    image: "redis:alpine"
  php:
    build: './docker/php'
    volumes:
      - .:/var/www/html
      - /var/www/html/var/cache
      - /var/www/html/var/log
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080