easy_admin:
    user:
        display_name: true
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - email
                    - profile.firstName
                    - profile.lastName
                    - reviews
            form:
                fields:
                    - email
                    - password
                    - { property: profile, type: App\Form\UserProfileType }