easy_admin:
    user:
        display_name: true
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
            controller: App\Controller\Admin\UserController
            list:
                fields:
                    - id
                    - { property: 'profile.avatar', type: 'image', base_path: '%app.path.images%' }
                    - email
                    - profile.firstName
                    - profile.lastName
                    - reviews
            new:
                form_options: { validation_groups: ['create'] }
            form:
                fields:
                    - email
                    - { property: profile, type: App\Form\UserProfileType }